### PR TITLE
Fiex#308

### PR DESCRIPTION
**Pull request by huang12zheng**
Describe the purpose of the pull request.
- Fixed ... was  #308

### CODE REVIEW

**Comment by mainawycliffe** [comment]
Hi, make the changes against beta please.

**Comment by huang12zheng** [comment]
thanks for the warning

**Comment by mainawycliffe** [comment]
@huang12zheng  you can change the target without closing the PR

**Comment by huang12zheng** [comment]
OK,I know it.




------------------ 原始邮件 ------------------
发件人: "Maina Wycliffe"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 晚上9:08
收件人: "zino-app/graphql-flutter"<graphql-flutter@noreply.github.com>; 
抄送: "One by one?"<805104533@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zino-app/graphql-flutter] Fiex#308 (#316)




@huang12zheng  you can change the target without closing the PR

**Comment by mainawycliffe** [comment]
Why did you close it. Everything looked good, apart from the target branch.

**Comment by huang12zheng** [comment]
sorry,I don't know how to change the target.  and just make a new PR

**Comment by huang12zheng** [comment]
and make comment simple.

**Comment by mainawycliffe** [comment]
Cool. Approved the changes on the new PR.

**Comment by mainawycliffe** [comment]
Closed in favor of https://github.com/zino-app/graphql-flutter/pull/317

**Pull request closed without merging**
