### PR TITLE
[beta] remove bloc variable and used blocprovider.of

### PR DESCRIPTION
**Pull request by Abhishek01039**
There is Close instances of dart.core.Sink.dartclose_sinks warning.
So I have removed the bloc variable and directly used BlocProvider.of.

Fixes / Enhancements
refactored to avoid "Close instances of dart.core.Sink.dartclose_sinks" warning

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @micimize 
can you please review this PR?
Thanks

**Review by micimize — APPROVED** [review]

**Comment by Abhishek01039** [comment]
Thanks @HofmannZ

**Pull request merged**
