### PR TITLE
expose runQuery Method to trigger Query Manually

### PR DESCRIPTION
**Pull request by echonox**
Describe the purpose of the pull request.

### Breaking changes
This changes breaks the basic query api, now it adds an `runQuery` extra param in the builder list of parameters

#### Fixes / Enhancements

- Adds the ability to trigger the query manually, until now it would require to call the client manually, or use a poll interval to update the refetch the query

#### Docs

- Before:

```dart
...

Query(
  readRepositories, // this is the query you just created
  variables: {
    'nRepositories': 50,
  },
  pollInterval: 10, // optional
  builder: ({
    bool loading,
    var data,
    Exception error
  }) {
    if (error != null) {
      return Text(error.toString());
    }

    if (loading) {
      return Text('Loading');
    }

    // it can be either Map or List
    List repositories = data['viewer']['repositories']['nodes'];

    return ListView.builder(
      itemCount: repositories.length,
      itemBuilder: (context, index) {
        final repository = repositories[index];

        return Text(repository['name']);
    });
  },
);

...
```

After:

```dart
...

Query(
  readRepositories, // this is the query you just created
  variables: {
    'nRepositories': 50,
  },
  pollInterval: 10, // optional
  builder: ({
    bool loading,
    var data,
    Exception error,
    runQuery
  }) {
    if (error != null) {
      return Text(error.toString());
    }

    if (loading) {
      return Text('Loading');
    }

    // it can be either Map or List
    List repositories = data['viewer']['repositories']['nodes'];

    return ListView.builder(
      itemCount: repositories.length,
      itemBuilder: (context, index) {
        final repository = repositories[index];

        return Text(repository['name']);
    });
  },
);

...
```

### CODE REVIEW

**Comment by juicycleff** [comment]
I think refetch would be a better method to expose based on the apollo client design. I am currently implementing this future in my fork

**Comment by echonox** [comment]
@juicycleff agree on that, shouldn't we have a strict naming for the api? as some methods aren't following the apollo client design, also I see your fork is way ahead of the main repo, and it seems you are using streams (bloc pattern), should we use your fork in production or stick with the main?

**Comment by juicycleff** [comment]
To be honest, I just felt the revision process takes a long time here, and I've needed this library as mature as soon as possible, so my fork is a little bit different and merging back here will be a little harder than anticipated. I currently use my fork in production and is still WIP, however, I duplicated my fork to my company Org so as to get more contributors as it's a little bit organized differently from this. You can use mine if you wish, I published with flutter_graphql, but there's still a lot to be done.

**Comment by juicycleff** [comment]
The project lives here now https://github.com/snowballdigital/flutter-graphql

**Comment by micimize** [comment]
@echonox This is good, but active development is on `next`. I've gone ahead and implemented `refetch` on a fork from there and will be PRing soon 👍 

On `next`, `runMutation` is positional, and thus closer to the original apollo API.

**Pull request closed without merging**
