### PR TITLE
feat(client): cache is supported in web/browser platform

### PR DESCRIPTION
**Pull request by truongsinh**
This is an ongoing effort to make this package compatible to web/browser #295.

In web/browser platform, Cache is supported by `localStorage`.

The naming `InMemoryCache` is also debatable, as both `io` and `html`
implementation of this class is based on "persistent storage", not at all
"in memory".

There are refactor works to do to consolidate `in_memory_*` files.

### Breaking changes

`InMemoryCache` no longer accept `storageProvider`,
however this param has always been using for testing only.

### CODE REVIEW

**Comment by micimize** [comment]
This is related to #297 - I really think caching is worth breaking into a separate module https://pub.dev/packages/caches

anyways @truongsinh I'm guessing rebasing will resolve these conflicts and then I can re-approve and merge

**Comment by truongsinh** [comment]
@micimize please be aware that I have a new commit, now the test is running in headless Chromium as well

**Pull request merged**
