### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Anirban-Chand**
Small spelling correction

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
LGTM thanks

**Comment by vincenzopalazzo** [comment]
We will prefer this PR instead to https://github.com/zino-app/graphql-flutter/pull/970 for the following reason:

-  It is an older PR, so https://github.com/zino-app/graphql-flutter/pull/970 it is a duplicate;
- This contains more detail on the changes.

Thank you to contribute.

**Comment by vincenzopalazzo** [comment]
Can you Rebase on the actual version of the beta branch @Anirban-Chand ?

**Comment by Anirban-Chand** [comment]
> Can you Rebase on the actual version of the beta branch @Anirban-Chand ?

how to do that?

**Comment by vincenzopalazzo** [comment]
>how to do that?

Maybe this can help https://stackoverflow.com/questions/40009820/git-rebase-one-branch-on-top-of-another-branch/40009875

Or if you have problem I can cherry-pick your commits to include it in another pr with your as author!

**Comment by Anirban-Chand** [comment]
> > how to do that?
> 
> Maybe this can help https://stackoverflow.com/questions/40009820/git-rebase-one-branch-on-top-of-another-branch/40009875
> 
> Or if you have a problem I can cherry-pick your commits to include it in another pr with you as author!

It will be very kind of you if you please include my commits. Thank You!

**Comment by vincenzopalazzo** [comment]
Thanks for contributing, I included your commit here https://github.com/zino-app/graphql-flutter/pull/982 and I'm closing this PR :) thanks

**Comment by Anirban-Chand** [comment]
> Thanks for contributing, I included your commit here #982 and I'm closing this PR :) thanks

You're welcome 🤗

**Pull request closed without merging**
