### PR TITLE
fix: ignore `.idea` directory

### PR DESCRIPTION
**Pull request by klavs**
`.idea/modules.xml` at the current state is incorrect and useless
remove `.idea` directory and ignore it

Describe the purpose of the pull request.

### CODE REVIEW

**Comment by HofmannZ** [comment]
@klavs Thanks for the PR, please rebase on beta, we had to fix the coverage collection in the pipeline.

**Comment by klavs** [comment]
rebased on beta

cc @HofmannZ @mainawycliffe

**Comment by HofmannZ** [comment]
@klavs was about to his merge, but commit is not signed 😕

**Comment by klavs** [comment]
@HofmannZ signed. That requirement should be document somewhere.

**Pull request merged**
