### PR TITLE
added an abstract method to the cache

### PR DESCRIPTION
**Pull request by juicycleff**
This PR is a minor adjustment to the cache abstract class for the implementation of SQL normalized disk cache

### Breaking changes
Added the remove method to the Cache abstract class.

### CODE REVIEW

**Comment by micimize** [comment]
Looking at the [full diff of `v1` vs `next`](https://github.com/zino-app/graphql-flutter/compare/next...juicycleff:v1.0.0) puts this more in context - you've got quite a lot done over there and now we have to figure out the best approach for merging it back in.

@juicycleff Could you break out your changes into larger feature-oriented PRs, like maybe one for all the changes need for the functioning SQL cache, one for the socket/subscription features, etc?

I'll try and contribute as much as I can to getting it all reviewed, documented, and merged

**Comment by juicycleff** [comment]
I feel like the review tames too long. I needed to move on with my project, so I just improved my fork a little bit more adding more apollo react like features. I will try to do that, after I add refetch and network status which I am working on now

**Comment by juicycleff** [comment]
I do have two forks, one which is released separately from this and another that links to this

**Comment by micimize** [comment]
@juicycleff sounds good - yeah I'll try and get to it faster next time. I see you've started adding docs to master, so maybe once all those changes are documented enough you can PR that and we can move forward from there.

 I'm going to go ahead and close this, as on it's own it'll break the build.

**Pull request closed without merging**
