### PR TITLE
Structural data validation on cache writes and more

### LINKED ISSUE #747: [v4] Both result data and exception are sometimes null on network result
**Describe the bug**
Just upgraded to graphql_flutter: `^4.0.0-beta.3`. What I did  is a normal query as I did before.

I'm not sure what is the problem.
```graphql
query {
  userByToken {
    newOrders(query: {skip: 0, sortBy: "createdAt", order: 1}) {
      id
      dishMetas {
        dish {
          id
          name
          store {
            id
            name
            description
            avatar
            district {
              name
            }
          }
          tag
          price
          avatar
        }
        quantity
        remark
      }
      status
      initiator {
        id
        name
        tel
        address
      }
      deliverPrice
      createdAt
    }
  }
}
```
I do the same query in postman which is all fine. 
I wonder in what situation this data would be null? isLoading is false, and there is no exception. Having worked on it for hours and have no clue.

### PR DESCRIPTION
**Pull request by micimize**
Closes #747, #744, #718, #683, #687, #616, #405 

depends on https://github.com/gql-dart/ferry/pull/104

### `result.data` carry forward on exception (#718)
for `watchQuery`, when an exception results in `null` data, the previous result will be used by default. Can be disabled by `WatchQueryOptions(carryForwardDataOnException: false)`

### only rebroadcast when !deep equals by default (#616)
`alwaysRebroadcast` can be used to get the old behavior back.

### strict cache writes (semi-breaking)
cache writes are now strict and throw PartialDataException (from normalize) or a CacheMisconfigurationException if the structures seem like they should be valid (configurable by `partialDataPolicy`)

At link execution time, one of the following exceptions can be thrown:
* CacheMisconfigurationException if the structure seems like it should
   write properly.
* UnexpectedResponseStructureException if the server response looks malformed.
* MismatchedDataStructureException in the event of a malformed
   optimistic result.
* If write succeeds but `readQuery` then returns `null`, a `CacheMissException` will be added and **the data will not be overwritten**

before, one could attempt to write any data structure to the cache, and it would write whatever document-matching data there was.
Now, if one attempts to write structurally partial data, appropriate
exceptions will be thrown.

### fechMore updates
* Corresponding to the above, `FetchMoreOptions.partial` is added for safer update operations
* unrelatedly, `UpdateQuery` is now strictly typed with `Map`s

### Skip cache writes when errors && ErrorPolicy.none (#405)
```
  /// If we have no data, we skip caching, thus taking [ErrorPolicy.none]
  /// into account
```

I also verified `examples/starwars` works on web and bumped the connectivity plugin to silence an error.

### CODE REVIEW

**Comment by micimize** [comment]
This depends on https://github.com/gql-dart/ferry/pull/104 getting merged, but can be tried out like so:
```yaml
dependency_overrides:
  graphql:
    git: 
      url: git@github.com:micimize/graphql-flutter.git
      ref: norm_data_handling
      path: packages/graphql
```

**Comment by micimize** [comment]
Note to self: Update Exceptions section with strictness errors https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#exceptions

**Comment by EightRice** [comment]
I got here cause Uncaught (in promise) Error: Expected a value of type 'String', but got one of type 'NativeJavaScriptObject'
and this was supposed to be the solution... I have no idea what all this text is but if anyone can kindly tell me what to do about my error, I'd be really grateful.

**Comment by micimize** [comment]
@EightRice open a new issue – that sounds like a web-related issue and at first blush doesn't look necessarily related to strict cache writes (maybe that's why the error was surfaced, but not the root cause)

**Pull request merged**
