### PR TITLE
fixed flutter bloc example

### PR DESCRIPTION
**Pull request by vasilich6107**
### Breaking changes
- no breaking changes

#### Fixes / Enhancements
- updated deps
- added extended bloc example with fetchMore and refetch

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hi @mainawycliffe 
Could you look at my PR?

I fixed some minor things in your example caused by packages update and added extended example with `refetch` and `fetchMore` implementation.

**Comment by micimize** [comment]
@vasilich6107 https://github.com/artflutter/graphql-flutter/pull/1
> Either rebase changes from master or give me permissions to, and then we can merge this

**Comment by vasilich6107** [comment]
@micimize granted access to you

**Pull request merged**
