### PR TITLE
Check for nullable keepAliveSubscription

### PR DESCRIPTION
**Pull request by phuchuynhStrong**
Check for nullable ```keepAliveSubscription``` when disposing ```SocketClient```.

**Fixes**
- Fixed ```dispose``` function of ```SocketClient```, it didn't check the nullable ```keepAliveSubscription``` before put it into ```Future.wait```.  If ```SocketClientConfig``` constructed with null ```inactivityTimeout```, ```keepAliveSubscription``` won't be initialized which results in the exception in ```Future.wait```.

### CODE REVIEW

**Comment by micimize** [comment]
if this is an issue it would be better to apply it to all the items in the list, as they all appear to be nullable. Something like ` Future.wait([...].where((closing) => closing != null)).toList())`

**Comment by phuchuynhStrong** [comment]
Yup. It's better approach to handle this func. I updated the code.

**Review by micimize — APPROVED** [review]

**Pull request merged**
