### PR TITLE
Capture stack traces in UnknownExceptions

### PR DESCRIPTION
**Pull request by shyndman**
#### Fixes / Enhancements
- Added 
We've been running into exceptions that are pretty tricky to nail down without more context, and I was thinking that the inclusion of stack traces in UnknownExceptions would be helpful for us, and everybody else!

Related to https://github.com/nhost/nhost-dart/issues/9

### CODE REVIEW

**Review by micimize — APPROVED** [review]
god yes. This should really be done for all exceptions at the `gql` interface level imo

**Review by micimize — APPROVED** [review]

**Review by micimize — APPROVED** [review]

**Comment by shyndman** [comment]
Thank you. :)

**Comment by shyndman** [comment]
Version 5.0.0! YESSS!

(I'm actually pumped about this. No more warnings from pub!)

**Pull request merged**
