### PR TITLE
refine type check in _recursivelyAddAll to prevent type error

### LINKED ISSUE #676: Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
Query used
```
query ($cursor: Int) {
      posts(cursor: $cursor) {
        id
        title
        content
        source
        user {
          name
        }
      }
    }
```

```
E/flutter (24950): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter (24950): #0      _recursivelyAddAll.<anonymous closure> (package:graphql/src/utilities/helpers.dart:20:21)
E/flutter (24950): #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (24950): #2      _recursivelyAddAll (package:graphql/src/utilities/helpers.dart:14:10)
E/flutter (24950): #3      ListMixin.reduce (dart:collection/list.dart:208:22)
E/flutter (24950): #4      deeplyMergeLeft (package:graphql/src/utilities/helpers.dart:48:53)
E/flutter (24950): #5      GraphQLCache.writeNormalized (package:graphql/src/cache/cache.dart:100:28)
E/flutter (24950): #6      NormalizingDataProxy.writeQuery.<anonymous closure> (package:graphql/src/cache/_normalizing_data_proxy.dart:95:34)
E/flutter (24950): #7      normalize.<anonymous closure> (package:normalize/src/normalize.dart:139:47)
E/flutter (24950): #8      Iterable.forEach (dart:core/iterable.dart:279:30)
E/flutter (24950): #9      normalize (package:normalize/src/normalize.dart:139:22)
E/flutter (24950): #10     NormalizingDataProxy.writeQuery (package:graphql/src/cache/_normalizing_data_proxy.dart:94:5)
E/flutter (24950): #11     QueryManager.addQueryResult (package:graphql/src/core/query_manager.dart:290:13)
E/flutter (24950): #12     fetchMoreImplementation (package:graphql/src/core/fetch_more.dart:57:18)
E/flutter (24950): <asynchronous suspension>
E/flutter (24950): #13     ObservableQuery.fetchMore (package:graphql/src/core/observable_query.dart:208:12)
E/flutter (24950): #14     HomeQueryBuilderState._fetchMore (package:pondr/screens/home.dart:158:21)
E/flutter (24950): #15     HomeQueryBuilderState._onPageChanged (package:pondr/screens/home.dart:195:7)
E/flutter (24950): #16     _SwipeViewState.animationSideEffects (package:pondr/widgets/swipe_view.dart:250:58)
E/flutter (24950): #17     _SwipeViewState.runAnimation (package:pondr/widgets/swipe_view.dart:227:7)
E/flutter (24950): #18     AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:135:19)
E/flutter (24950): #19     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:792:5)
E/flutter (24950): #20     Ticker._tick (package:flutter/src/scheduler/ticker.dart:237:12)
E/flutter (24950): #21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
E/flutter (24950): #22     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1028:11)
E/flutter (24950): #23     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (24950): #24     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1026:17)
E/flutter (24950): #25     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:960:5)
E/flutter (24950): #26     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (24950): #27     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (24950): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (24950): #29     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (24950): #30     _beginFrame (dart:ui/hooks.dart:202:3)
E/flutter (24950): 
```

graphql_flutter: 4.0.0-alpha.0
flutter: 1.17.3

### PR DESCRIPTION
**Pull request by vemarav**
Fixed #676

### CODE REVIEW

**Comment by micimize** [comment]
Oh wait, I'm going to have to investigate this a bit more. If the keys of `target[key]` are of type `dynamic`, then  `target[key] is Map<String, dynamic>` will fail. So, this might be solving the error, might also be totally breaking `_recursivelyAddAll`

**Comment by vemarav** [comment]
@micimize :+1:

**Pull request merged**
