### PR TITLE
Add refetch to QueryResult

### PR DESCRIPTION
**Pull request by lohmander**
Adding a refetch function to QueryResult. Perhaps there's another better way that also can be easily implemented, but this seems to do the job for now.

### Breaking changes

No breaking changes.

#### Fixes / Enhancements

- Added `refetch` to QueryResult

#### Docs

None (yet).

### CODE REVIEW

**Comment by venkatd** [comment]
@lohmander we need this as well! Is there anything remaining to be done here?

Happy to help get this merged however I can.

**Comment by olup** [comment]
Just a note, maybe api for `refetch` and `fetchMore` should be provided in a coherent way ? See #144

**Comment by lohmander** [comment]
@venkatd I've not had time to familiarize myself with the codebase as a whole, so this solution might not be inline with that the package authors have in mind. But it does the job and we already use the fork in a production app.

**Comment by HofmannZ** [comment]
Closing this PR for now and continuing discovery on issue #144.

**Pull request closed without merging**
