### PR TITLE
Update Beta with Commits on Master

### PR DESCRIPTION
**Pull request by mainawycliffe**
This PR seeks to ensure that beta branch is not behind master branch.

### CODE REVIEW

**Comment by micimize** [comment]
@mainawycliffe did you mean to target `beta`?

**Comment by mainawycliffe** [comment]
Yea, sorry.

**Comment by HofmannZ** [comment]
This happens automatically on each release

**Comment by HofmannZ** [comment]
I see I forgot to check the commit messages in the PRs by @truongsinh, those were not formatted conform spec, an therefore did not trigger the release.

**Comment by mainawycliffe** [comment]
Yea, is there a way of automatically checking the commit messages?

**Comment by mainawycliffe** [comment]
@HofmannZ have a look at this https://github.com/antham/gommit

**Pull request closed without merging**
