### PR TITLE
perf: open Hive boxes concurrently

### PR DESCRIPTION
**Pull request by Ascenio**
This PR reduces initialization time taken by `initHiveForFlutter`.

### Breaking changes

- None.

#### Fixes / Enhancements

- Changed `initHiveForFlutter` to open boxes concurrently using [Future.wait](https://api.dart.dev/stable/2.13.4/dart-async/Future/wait.html)

#### Docs

- No changes.

### CODE REVIEW

**Review by budde377 — DISMISSED** [review]

**Comment by budde377** [comment]
LGTM, thanks for the contribution!

**Comment by vincenzopalazzo** [comment]
Can you fix your commit signature @Ascenio ?

**Comment by Ascenio** [comment]
It seems like the tests failed because they ping `ws://echo.websocket.org` which is no longer available. :laughing:

**Comment by vincenzopalazzo** [comment]
>It seems like the tests failed because they ping ws://echo.websocket.org which is no longer available. laughing

Yes, now the test of the ws are disabled, we will enable it when we will migrate to Github action. However, if you rebase your PR on master this error should be over.

**Review by vincenzopalazzo — DISMISSED** [review]
LGTM, need only a rebase on top of beta branch

**Review by vincenzopalazzo — APPROVED** [review]
Awesome, thanks for contributing into the repository.

**Comment by vincenzopalazzo** [comment]
@Ascenio here there is some problem with the signed commit, maybe this can help you? https://docs.github.com/articles/about-gpg

**Review by budde377 — APPROVED** [review]

**Review by vincenzopalazzo — APPROVED** [review]
Awesome, thanks.

LTGM

**Pull request merged**
