### PR TITLE
added articles section to the main read me file 

### PR DESCRIPTION
**Pull request by vasilich6107**
the article which covers basic flow of usage graphql_flutter in flutter ecosystem

#### Docs

- added articles section to the main read me file

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hi @mainawycliffe 
Could you look at my PR?

**Comment by micimize** [comment]
@vasilich6107 There are a few grammatical mistakes in the article – can we [sync up on discord](https://discord.gg/tXTtBfC) and we'll do revision via google docs or something? most notably
* `graphql_flutter` is referred to as `flutter_graphql` a lot
* `pubspeck.yaml` should be `pubspec.yaml`

**Pull request merged**
