### PR TITLE
Eager results, QueryResultSource, MultiSourceResult runMutation future

### LINKED ISSUE #153: Don't hide loading state
If a query is loading but was found from cache the current implementation tells us that the loading is false.

I'd like if this app would report errors, loading and data independently because there may be a case where a query has data from cache and is loading and I'd like to display a loading indicator alongside the data to show that it is loading and if this query errors I'd like to show the error but not stop showing the cached data.

What's your take on this API change? I'm using a fork that does this and if you agree on this change of the API I could submit a PR with it.

### PR DESCRIPTION
**Pull request by micimize**
Closes #153, #273, #290 

### Breaking changes

- Renamed `ObservableQuery.previousResult` `ObservableQuery.latestResult`
- Removed `QueryManager.addOptimisticQueryResult` and privatized it's logic

#### Fixes / Enhancements
- Added `QueryResultSource` and `QueryResult.source` for more fine-grained result typing (#153)
- Added `MultiSourceResult` to allow eager/synchronous code paths
- Added `QueryManager.fetchQueryAsMultiSourceResult` (name up for debate)
  - refactored eager logic into `_eagerlyResolveQuery`
  - refactored network logic into `_resolveQueryOnNetwork`
  - `fetchQuery` now thinly wraps `...AsMultiSourceResult`
- `ObservableQuery.fetchResults` and `Mutation.runMutation` now return `MultiSourceResult` (#273)
- Added `WatchQueryOptions.eagerlyFetchResults` for fine-grained first-fetch control
- `Query` and `Mutation` `initialData` are now the `latestResult` if available (#290)

### CODE REVIEW

**Comment by micimize** [comment]
validated against example and all the routes in my code, but didn't try using the `runMutation`. `MultiSourceResult` - @smkhalsa or @joprice's feedback / testing would be appreciated there.

**Comment by joprice** [comment]
I won't have time for a bit to try this out, but it looks good. Should the example that ends up showing up https://pub.dev/packages/graphql_flutter include usage of this feature?

**Comment by micimize** [comment]
@joprice more examples are always good, but it's all a matter of time and resources.
We really need more examples and docs for most of the API in general ( #59 )

The shorthand usage doc for the `runMutation` change is roughly
```dart
MultiSourceResult results = runMutation(/*...*/);
QueryResult eagerResult = results.eagerResult;
// make some optimistic updates, or
QueryResult finalResult = await results.networkResult;
// and stop a spinner or something
```

**Pull request merged**
