### PR TITLE
Ignore remaining idea files and fix example pubspec path

### PR DESCRIPTION
**Pull request by camuthig**
I know these two concepts are not generally related, but they were both very simple. Willing to split them up if you would prefer.

### CODE REVIEW

**Comment by HofmannZ** [comment]
I held back on those remaining files, because they don't reference any local files. Is there any specific reason why they should not be kept in version control?

> I use VS Code myself so I'm a little bit cautious removing files for other IDE.

**Comment by camuthig** [comment]
I removed them at the suggestion of the IntelliJ documentation: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems .

**Comment by HofmannZ** [comment]
Thanks for the link, makes sense to remove it since it's recommended.

**Pull request merged**
