### PR TITLE
Reconnect websocket subscription

### PR DESCRIPTION
**Pull request by MSchmack**
Updating the subscription data when the user goes from offline to an online state with an ongoing subscription.

#### Fixes / Enhancements

Solution for issue #364 
Checks when to reconnect with the connectivity plugin. Calls _initSubscription when internet should be available again.

> Note that on Android, this does not guarantee connection to Internet. For instance, the app might > have wifi access but it might be a VPN or a hotel WiFi with no access.
Uses a nslookup on connectivitychange for android as solution to the shortcoming of the connectivity plugin.

It might be wise to make the android nslookup optional for users that want to reduce traffic, even if minimal.

#### Docs

No document change needed as this functionality is already implied with the flag autoReconnect.

### CODE REVIEW

**Comment by HofmannZ** [comment]
@MSchmack Still missing tests.

**Comment by MSchmack** [comment]
@HofmannZ There are no tests in the graphql_flutter project for the different widgets so none have been expanded. Do you test the widgets at a different location?

https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter/test

**Comment by HofmannZ** [comment]
@MSchmack My apologies I thought this was for the subscription client. LGTM.

**Comment by smkhalsa** [comment]
@HofmannZ shouldn't this be added to the client rather than the widget directly?

**Comment by ryankauk** [comment]
Is there an estimated time when this would reach stable?

**Pull request merged**
