### PR TITLE
fix(client): use http 0.12.0+4 to fix a wrong content-type header on multipart request on http 0.12.0+3

### LINKED ISSUE #525: multipart_upload_test fails
**Describe the bug**
`graphql/test/multipart_upload_test` fails at line 161 because `application/json` is returned instead of `multipart/form-data`.

**To Reproduce**
1. cd graphql-flutter/packages/graphql
1. pub run test_coverage
1. Interrupt as soon as `.test_coverage.dart` is generated.
1. Run test manually using:
    dart --pause-isolates-on-exit \\
        --enable_asserts \\
        --enable-vm-service=8787 test/.test_coverage.dart

The relevant section of the test output is as follows:

```
00:01 +64 -1: upload upload success [E]
  Expected: 'multipart/form-data'
    Actual: 'application/json'
     Which: is different.
            Expected: multipart/ ...
              Actual: applicatio ...
                      ^
             Differ at offset 0

  package:test_api/src/frontend/expect.dart 153:30              fail
  package:test_api/src/frontend/expect.dart 147:3               _expect
  package:test_api/src/frontend/expect.dart 59:3                expect
  test/multipart_upload_test.dart 161:7                         main.<fn>.<fn>
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 2.1.1-beta.5

**Additional context**
- [Test coverage full output](https://github.com/zino-app/graphql-flutter/files/4027066/test_coverage.txt)

### PR DESCRIPTION
**Pull request by knaeckeKami**
Fixes #525.

### CODE REVIEW

**Comment by mainawycliffe** [comment]
Thanks for the PR, can you rebase against beta, please. Its the branch that has the issue.

**Comment by knaeckeKami** [comment]
This PR should be merged into beta, shouldn't it?
Sorry, seems like we edited the PR concurrently and now it's a bit of a mess.

**Comment by mainawycliffe** [comment]
Yeah, the tests are failing on beta and not master. If everything works on beta, then we can approve the other PRs waiting before promoting to master.

**Comment by mainawycliffe** [comment]
> Sorry, seems like we edited the PR concurrently and now it's a bit of a mess.

No problem, let's wait and see everything completes successfully

**Comment by mainawycliffe** [comment]
@knaeckeKami This PR is failing some tests because it was created from the master branch instead of the current beta branch. I think you should create a new branch from beta, make the changes and create the PR again. This way, it will be easier to merge as I suppose all tests will purpose and code coverage will not be affacted.

**Comment by knaeckeKami** [comment]
yeah, i created it from master. i opened a new, clean PR

**Pull request closed without merging**
