### PR TITLE
Promote Beta to Stable

### PR DESCRIPTION
**Pull request by HofmannZ**
This PR promotes `beta` to `stable`, which will be released on our next release cycle (Monday the 12th of August.)

### CODE REVIEW

**Comment by mainawycliffe** [comment]
is it possible to update install versions in read me automatically when a new version is released?

**Comment by HofmannZ** [comment]
Coverage went down 1% 😕.

**Comment by HofmannZ** [comment]
> is it possible to update install versions in read me automatically when a new version is released?

@mainawycliffe I can see what I can do.

**Comment by mainawycliffe** [comment]
> Coverage went down 1% 😕.

I can work on improving this.

**Comment by mainawycliffe** [comment]
We probably should merge this [PR ](https://github.com/zino-app/graphql-flutter/pull/378)to beta first, as it contains some docs update.

**Pull request merged**
